export const dataWorld = [
	{
		english: 'the',
		portuguese: 'o, a, os, as',
		exampleEn: 'The cat is sleeping on the sofa.',
		examplePt: 'O gato está dormindo no sofá.',
	},
	{
		english: 'be',
		portuguese: 'ser, estar',
		exampleEn: 'I want to be a teacher.',
		examplePt: 'Eu quero ser professor.',
	},
	{
		english: 'to',
		portuguese: 'para, a',
		exampleEn: 'I’m going to the store.',
		examplePt: 'Eu vou para a loja.',
	},
	{
		english: 'of',
		portuguese: 'de',
		exampleEn: 'A piece of cake.',
		examplePt: 'Um pedaço de bolo.',
	},
	{
		english: 'and',
		portuguese: 'e',
		exampleEn: 'She and her brother live here.',
		examplePt: 'Ela e seu irmão moram aqui.',
	},
	{
		english: 'a',
		portuguese: 'um, uma',
		exampleEn: 'He has a dog.',
		examplePt: 'Ele tem um cachorro.',
	},
	{
		english: 'in',
		portuguese: 'em, dentro',
		exampleEn: 'She is in the kitchen.',
		examplePt: 'Ela está na cozinha.',
	},
	{
		english: 'that',
		portuguese: 'que, aquilo',
		exampleEn: 'I know that you’re right.',
		examplePt: 'Eu sei que você está certo.',
	},
	{
		english: 'have',
		portuguese: 'ter',
		exampleEn: 'They have two cars.',
		examplePt: 'Eles têm dois carros.',
	},
	{
		english: 'I',
		portuguese: 'eu',
		exampleEn: 'I like this song.',
		examplePt: 'Eu gosto desta música.',
	},
	{
		english: 'it',
		portuguese: 'isso, ele, ela (neutro)',
		exampleEn: 'It is raining outside.',
		examplePt: 'Está chovendo lá fora.',
	},
	{
		english: 'for',
		portuguese: 'para, por',
		exampleEn: 'This gift is for you.',
		examplePt: 'Este presente é para você.',
	},
	{
		english: 'not',
		portuguese: 'não',
		exampleEn: 'I do not understand.',
		examplePt: 'Eu não entendo.',
	},
	{
		english: 'on',
		portuguese: 'sobre, em cima de',
		exampleEn: 'The book is on the table.',
		examplePt: 'O livro está sobre a mesa.',
	},
	{
		english: 'with',
		portuguese: 'com',
		exampleEn: 'I’m going with my friend.',
		examplePt: 'Eu vou com meu amigo.',
	},
	{
		english: 'he',
		portuguese: 'ele',
		exampleEn: 'He works in a bank.',
		examplePt: 'Ele trabalha em um banco.',
	},
	{
		english: 'as',
		portuguese: 'como',
		exampleEn: 'As you know, I was late.',
		examplePt: 'Como você sabe, eu me atrasei.',
	},
	{
		english: 'you',
		portuguese: 'você, tu',
		exampleEn: 'You are very kind.',
		examplePt: 'Você é muito gentil.',
	},
	{
		english: 'do',
		portuguese: 'fazer',
		exampleEn: 'What do you want to eat?',
		examplePt: 'O que você quer comer?',
	},
	{
		english: 'at',
		portuguese: 'em, no, na',
		exampleEn: 'Meet me at the station.',
		examplePt: 'Me encontre na estação.',
	},
	{
		english: 'this',
		portuguese: 'este, esta',
		exampleEn: 'This is my favorite movie.',
		examplePt: 'Este é meu filme favorito.',
	},
	{
		english: 'but',
		portuguese: 'mas',
		exampleEn: 'I tried, but I failed.',
		examplePt: 'Eu tentei, mas falhei.',
	},
	{
		english: 'his',
		portuguese: 'dele',
		exampleEn: 'This is his book.',
		examplePt: 'Este é o livro dele.',
	},
	{
		english: 'by',
		portuguese: 'por, de, ao lado de',
		exampleEn: 'The song was written by him.',
		examplePt: 'A música foi escrita por ele.',
	},
	{
		english: 'from',
		portuguese: 'de, desde',
		exampleEn: 'I come from Brazil.',
		examplePt: 'Eu venho do Brasil.',
	},
	{
		english: 'they',
		portuguese: 'eles, elas',
		exampleEn: 'They are my friends.',
		examplePt: 'Eles são meus amigos.',
	},
	{
		english: 'we',
		portuguese: 'nós',
		exampleEn: 'We have dinner at 7pm.',
		examplePt: 'Nós jantamos às 19h.',
	},
	{
		english: 'say',
		portuguese: 'dizer',
		exampleEn: 'What did you say?',
		examplePt: 'O que você disse?',
	},
	{
		english: 'her',
		portuguese: 'dela, a ela',
		exampleEn: 'I saw her in the park.',
		examplePt: 'Eu a vi no parque.',
	},
	{
		english: 'she',
		portuguese: 'ela',
		exampleEn: 'She is very nice.',
		examplePt: 'Ela é muito simpática.',
	},
	{
		english: 'or',
		portuguese: 'ou',
		exampleEn: 'Do you want tea or coffee?',
		examplePt: 'Você quer chá ou café?',
	},
	{
		english: 'an',
		portuguese: 'um, uma (antes de vogal)',
		exampleEn: 'She adopted an elephant.',
		examplePt: 'Ela adotou um elefante.',
	},
	{
		english: 'will',
		portuguese: 'vai, será',
		exampleEn: 'I will call you tomorrow.',
		examplePt: 'Eu te ligarei amanhã.',
	},
	{
		english: 'my',
		portuguese: 'meu, minha',
		exampleEn: 'This is my house.',
		examplePt: 'Esta é a minha casa.',
	},
	{
		english: 'one',
		portuguese: 'um, uma (quantidade)',
		exampleEn: 'I have one brother.',
		examplePt: 'Eu tenho um irmão.',
	},
	{
		english: 'all',
		portuguese: 'todo, todos',
		exampleEn: 'All of us came together.',
		examplePt: 'Todos nós viemos juntos.',
	},
	{
		english: 'would',
		portuguese: 'iria, seria',
		exampleEn: 'I would like some water, please.',
		examplePt: 'Eu gostaria de água, por favor.',
	},
	{
		english: 'there',
		portuguese: 'lá, ali, existe',
		exampleEn: 'There is a book on the table.',
		examplePt: 'Há um livro sobre a mesa.',
	},
	{
		english: 'their',
		portuguese: 'deles, delas',
		exampleEn: 'Their car is red.',
		examplePt: 'O carro deles é vermelho.',
	},
	{
		english: 'what',
		portuguese: 'o que, qual',
		exampleEn: 'What are you doing?',
		examplePt: 'O que você está fazendo?',
	},
	{
		english: 'so',
		portuguese: 'então, tão',
		exampleEn: 'I was tired, so I slept early.',
		examplePt: 'Eu estava cansado, então dormi cedo.',
	},
	{
		english: 'up',
		portuguese: 'acima, levantar-se',
		exampleEn: 'Look up at the sky.',
		examplePt: 'Olhe para o céu.',
	},
	{
		english: 'out',
		portuguese: 'fora, sair',
		exampleEn: "Let's go out tonight.",
		examplePt: 'Vamos sair hoje à noite.',
	},
	{
		english: 'if',
		portuguese: 'se',
		exampleEn: 'If it rains, we’ll stay home.',
		examplePt: 'Se chover, ficaremos em casa.',
	},
	{
		english: 'about',
		portuguese: 'sobre, acerca de',
		exampleEn: 'Tell me about your day.',
		examplePt: 'Me conte sobre seu dia.',
	},
	{
		english: 'who',
		portuguese: 'quem',
		exampleEn: 'Who is that man?',
		examplePt: 'Quem é aquele homem?',
	},
	{
		english: 'get',
		portuguese: 'obter, conseguir, pegar',
		exampleEn: 'I need to get some sleep.',
		examplePt: 'Eu preciso pegar um pouco de sono.',
	},
	{
		english: 'which',
		portuguese: 'qual',
		exampleEn: 'Which color do you prefer?',
		examplePt: 'Qual cor você prefere?',
	},
	{
		english: 'go',
		portuguese: 'ir',
		exampleEn: 'I go to work by bus.',
		examplePt: 'Eu vou para o trabalho de ônibus.',
	},
	{
		english: 'me',
		portuguese: 'me, mim',
		exampleEn: 'Can you help me?',
		examplePt: 'Você pode me ajudar?',
	},
	{
		english: 'when',
		portuguese: 'quando',
		exampleEn: 'When is your birthday?',
		examplePt: 'Quando é seu aniversário?',
	},
	{
		english: 'make',
		portuguese: 'fazer, criar',
		exampleEn: 'Can you make a cake?',
		examplePt: 'Você pode fazer um bolo?',
	},
	{
		english: 'can',
		portuguese: 'poder',
		exampleEn: 'I can swim.',
		examplePt: 'Eu posso nadar.',
	},
	{
		english: 'like',
		portuguese: 'gostar, como',
		exampleEn: 'I like pizza.',
		examplePt: 'Eu gosto de pizza.',
	},
	{
		english: 'time',
		portuguese: 'tempo, hora',
		exampleEn: 'What time is it?',
		examplePt: 'Que horas são?',
	},
	{
		english: 'no',
		portuguese: 'não',
		exampleEn: 'No, thank you.',
		examplePt: 'Não, obrigado.',
	},
	{
		english: 'just',
		portuguese: 'apenas, somente',
		exampleEn: 'I just want to rest.',
		examplePt: 'Eu só quero descansar.',
	},
	{
		english: 'him',
		portuguese: 'ele, dele',
		exampleEn: 'Give it to him.',
		examplePt: 'Dê isso a ele.',
	},
	{
		english: 'know',
		portuguese: 'saber, conhecer',
		exampleEn: 'Do you know her?',
		examplePt: 'Você a conhece?',
	},
	{
		english: 'take',
		portuguese: 'tomar, levar',
		exampleEn: 'Take this book.',
		examplePt: 'Pegue este livro.',
	},
	{
		english: 'person',
		portuguese: 'pessoa',
		exampleEn: 'She is a good person.',
		examplePt: 'Ela é uma boa pessoa.',
	},
	{
		english: 'into',
		portuguese: 'para dentro de',
		exampleEn: 'He walked into the room.',
		examplePt: 'Ele entrou na sala.',
	},
	{
		english: 'year',
		portuguese: 'ano',
		exampleEn: 'She moved here last year.',
		examplePt: 'Ela se mudou para cá no ano passado.',
	},
	{
		english: 'your',
		portuguese: 'seu, sua, seus, suas',
		exampleEn: 'Is this your bag?',
		examplePt: 'Esta é sua bolsa?',
	},
	{
		english: 'good',
		portuguese: 'bom, boa',
		exampleEn: 'You did a good job.',
		examplePt: 'Você fez um bom trabalho.',
	},
	{
		english: 'some',
		portuguese: 'algum, alguns',
		exampleEn: 'I have some questions.',
		examplePt: 'Eu tenho algumas perguntas.',
	},
	{
		english: 'could',
		portuguese: 'poderia',
		exampleEn: 'Could you pass me the salt?',
		examplePt: 'Você poderia me passar o sal?',
	},
	{
		english: 'them',
		portuguese: 'eles, elas,-lhes',
		exampleEn: 'I saw them yesterday.',
		examplePt: 'Eu os vi ontem.',
	},
	{
		english: 'see',
		portuguese: 'ver',
		exampleEn: 'I see what you mean.',
		examplePt: 'Eu vejo o que você quer dizer.',
	},
	{
		english: 'other',
		portuguese: 'outro, outra',
		exampleEn: 'Do you have any other ideas?',
		examplePt: 'Você tem outras ideias?',
	},
	{
		english: 'than',
		portuguese: 'do que',
		exampleEn: 'She is taller than him.',
		examplePt: 'Ela é mais alta do que ele.',
	},
	{
		english: 'then',
		portuguese: 'então, depois',
		exampleEn: 'Then we will eat dinner.',
		examplePt: 'Então nós vamos jantar.',
	},
	{
		english: 'now',
		portuguese: 'agora',
		exampleEn: 'I need it now.',
		examplePt: 'Eu preciso disso agora.',
	},
	{
		english: 'look',
		portuguese: 'olhar',
		exampleEn: 'Look at that bird!',
		examplePt: 'Olhe aquele pássaro!',
	},
	{
		english: 'only',
		portuguese: 'somente, apenas',
		exampleEn: 'I only have one chance.',
		examplePt: 'Eu só tenho uma chance.',
	},
	{
		english: 'come',
		portuguese: 'vir',
		exampleEn: 'Come here, please.',
		examplePt: 'Venha aqui, por favor.',
	},
	{
		english: 'its',
		portuguese: 'seu, sua (neutro)',
		exampleEn: 'The cat chased its tail.',
		examplePt: 'O gato perseguiu seu rabo.',
	},
	{
		english: 'over',
		portuguese: 'sobre, acima, terminado',
		exampleEn: 'It’s over now.',
		examplePt: 'Já acabou agora.',
	},
	{
		english: 'think',
		portuguese: 'pensar',
		exampleEn: 'I think it’s a good idea.',
		examplePt: 'Acho que é uma boa ideia.',
	},
	{
		english: 'also',
		portuguese: 'também, além disso',
		exampleEn: 'She likes coffee. Also tea.',
		examplePt: 'Ela gosta de café. Também de chá.',
	},
	{
		english: 'back',
		portuguese: 'costas, de volta',
		exampleEn: 'I’ll be back soon.',
		examplePt: 'Eu voltarei logo.',
	},
	{
		english: 'after',
		portuguese: 'depois',
		exampleEn: 'After dinner, we watched a movie.',
		examplePt: 'Depois do jantar, assistimos a um filme.',
	},
	{
		english: 'use',
		portuguese: 'usar',
		exampleEn: 'You can use my phone.',
		examplePt: 'Você pode usar meu telefone.',
	},
	{
		english: 'two',
		portuguese: 'dois, duas',
		exampleEn: 'I have two apples.',
		examplePt: 'Eu tenho duas maçãs.',
	},
	{
		english: 'how',
		portuguese: 'como, quão',
		exampleEn: 'How are you doing?',
		examplePt: 'Como você está?',
	},
	{
		english: 'our',
		portuguese: 'nosso, nossa',
		exampleEn: 'This is our house.',
		examplePt: 'Esta é a nossa casa.',
	},
	{
		english: 'work',
		portuguese: 'trabalho, trabalhar',
		exampleEn: 'I go to work every day.',
		examplePt: 'Eu vou ao trabalho todo dia.',
	},
	{
		english: 'first',
		portuguese: 'primeiro, primeira',
		exampleEn: 'This is my first time here.',
		examplePt: 'Esta é minha primeira vez aqui.',
	},
	{
		english: 'well',
		portuguese: 'bem',
		exampleEn: 'She plays well.',
		examplePt: 'Ela joga bem.',
	},
	{
		english: 'way',
		portuguese: 'caminho, jeito, maneira',
		exampleEn: 'Is this the right way?',
		examplePt: 'Este é o caminho certo?',
	},
	{
		english: 'even',
		portuguese: 'mesmo, até, ainda',
		exampleEn: 'Even he could do it.',
		examplePt: 'Até ele poderia fazê-lo.',
	},
	{
		english: 'new',
		portuguese: 'novo, nova',
		exampleEn: 'I bought a new car.',
		examplePt: 'Eu comprei um carro novo.',
	},
	{
		english: 'want',
		portuguese: 'querer',
		exampleEn: 'I want to learn English.',
		examplePt: 'Eu quero aprender inglês.',
	},
	{
		english: 'because',
		portuguese: 'porque',
		exampleEn: 'I stayed home because I was tired.',
		examplePt: 'Fiquei em casa porque estava cansado.',
	},
	{
		english: 'any',
		portuguese: 'algum, qualquer',
		exampleEn: 'Do you have any questions?',
		examplePt: 'Você tem alguma pergunta?',
	},
	{
		english: 'these',
		portuguese: 'estes, estas',
		exampleEn: 'These apples are fresh.',
		examplePt: 'Estas maçãs estão frescas.',
	},
	{
		english: 'give',
		portuguese: 'dar',
		exampleEn: 'Give me a hand.',
		examplePt: 'Me dê uma mão.',
	},
	{
		english: 'day',
		portuguese: 'dia',
		exampleEn: 'Every day is a gift.',
		examplePt: 'Cada dia é um presente.',
	},
	{
		english: 'most',
		portuguese: 'a maioria, mais',
		exampleEn: 'Most people like music.',
		examplePt: 'A maioria das pessoas gosta de música.',
	},
	{
		english: 'us',
		portuguese: 'nós, nos',
		exampleEn: 'This affects us all.',
		examplePt: 'Isto nos afeta a todos.',
	},
] as const
